language: node_js
node_js:
  - 12
env:
   - DATABASE_URL=postgresql://postgres@localhost:5432/mybasket;
before_script:
  - psql -c 'create database mybasket' -U postgres  
  - psql -U postgres -d mybasket -a -f fruitSql.sql
 
services:
  - postgresql